[package]
name = "tkm"
version = "0.8.5"
authors = ["Sam Perlmutter <sam.perlmutter227@gmail.com>"]
edition = "2018"

[dependencies]
tui = "0.4.0"
termion = "1.5"
sysinfo = "0.8.*"
pretty-bytes = "0.2.2"
"nom" = "4.2.3"
