[package]
name = "task-manager"
version = "0.1.0"
authors = ["Sam Perlmutter <sam.perlmutter227@gmail.com>"]
edition = "2018"

[dependencies]
tui = {git = "https://github.com/fdehau/tui-rs"}
termion = {version = "1.5"}
