[package]
name = "tkm"
version = "0.1.0"
authors = ["Sam Perlmutter <sam.perlmutter227@gmail.com>"]
edition = "2018"

[dependencies]
tui = "0.4.0"
termion = "1.5"
sysinfo = "0.3.14"
itertools = "0.8"
failure = "0.1"
sys-info = "0.5.6"
pretty-bytes = "*"
